# Generated by Django 4.0.5 on 2022-08-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_book_name_alter_book_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('grnder', models.CharField(max_length=250)),
                ('dateofbirth', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('purpose', models.TextField()),
            ],
        ),
    ]
